# Generated by Django 6.0.4 on 2026-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_src', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
