# Generated by Django 6.0.4 on 2026-05-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_created_by_book_updated_at_book_updated_by'),
        ('books', '0002_remove_book_img_src_book_image'),
    ]

    operations = [
    ]
